module Autoflux
  module OpenAI
    VERSION: String

    class Error < StandardError
    end

    class AuthoriztionError < Error
    end

    class BadRequestError < Error
    end

    class RateLimitError < Error
    end
  end
end
